### ISSUE TITLE
open in colab badges not working

### ISSUE THREAD

**Issue by fcakyon** [gautamtata/DeepPlastic#2]
Hello thanks for the project,

urls for badges in readme are incorrect, it does not open your colab page.

**Comment by gautamtata** [comment]
Thanks, it should be fixed now. I removed the yolov4 link so that I can clean up the colab but added the yolov5 notebook.

**Comment by fcakyon** [comment]
@gautamtata the link you provided seems to be private, you have to make the colab url public i guess. It gives `you have no right`error.

**Comment by gautamtata** [comment]
Yep, I mentioned this in the readme but you have to click on file > save a copy to drive in order to access it yourself.

**Comment by gautamtata** [comment]
@fcakyon here's the link as well: https://colab.research.google.com/drive/1_qzbpBWkNfxQ0ny-DvsKicCeM0aFU4eW?usp=sharing

**Comment by fcakyon** [comment]
@gautamtata with this pr, it is cleaner i guess: https://github.com/gautamtata/DeepPlastic/pull/3

it doesnt require permission
