### ISSUE TITLE
Ultralytics blog post

### ISSUE THREAD

**Issue by glenn-jocher** [gautamtata/DeepPlastic#4]
@gautamtata hi we noticed this great use case for YOLOv5 and recently highlighted your work in a LinkedIn post:
https://www.linkedin.com/posts/ultralytics_ai-under-the-hood-object-detection-model-activity-6819273852980477952-Jt9C

We were wondering if you'd like to help use produce a blog post on ultralytics.com about how Vision AI can help clean the world's oceans. If you are interested please email me at glenn.jocher@ultralytics.com. Thank you!

**Comment by gautamtata** [comment]
Thanks for chatting today @glenn-jocher!

**Comment by glenn-jocher** [comment]
@gautamtata yeah thanks great chat!
